### ISSUE TITLE
can you please add following missing config items?

### ISSUE THREAD

**Issue by whiteshark-1975** [NzV/NecroBot-Settings-GUI#1]
"UpgradePokemonMinimumStatsOperator": "and",
  "KeepMinOperator": "or",

  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  
  "TotalAmountOfBerriesToKeep": 50,
 
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "UsePokemonSniperFilterOnly": false,

**Comment by NzV** [comment]
I will update it later today

**Comment by NzV** [comment]
Updated
